// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:bd4b077d-8a26-4988-b009-57b3d9d7a102",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_N4C29DjBM",
    "aws_user_pools_web_client_id": "2kdgq7uodd9sl8p8ke76rgibgm",
    "oauth": {}
};


export default awsmobile;
